### ISSUE TITLE
Stripe users lose their subscription again...

### ISSUE THREAD

**Issue by jayjay91** [strangerstudios/pmpro-gift-levels#32]
**Describe the bug**
V 0.3: "BUG FIX: Fixed bug where Gift Levels was not working with Stripe checkout for existing users. Users are no longer given an expiration date 3 days in the future."

This is precisely what is happening again since version 0.4.

**To Reproduce**
Use Stripe to get norma subscription
Buy gift subscription

**Comment by dparker1005** [comment]
I am doing some research into the history of this bug and keeping some notes here for the future. Here is the original GitHub issue for this bug: https://github.com/strangerstudios/pmpro-gift-levels/issues/8

**Here are all of the commits in v0.4:**
Avoid warning...
- https://github.com/strangerstudios/pmpro-gift-levels/commit/a19928254a5b428addd27fa28f83cad8c6fc3fa0
Change in discount code generation...
- https://github.com/strangerstudios/pmpro-gift-levels/commit/9dbaf8b013abcb57c775f8e254d03fd6111bb721
Changes filter that old membership is given back on...
- https://github.com/strangerstudios/pmpro-gift-levels/commit/ac19ec8d7f2c1caa5545ce3d73f9807becc8d6b3
Localization...
- https://github.com/strangerstudios/pmpro-gift-levels/commit/99c9f2d0f153868ee551c291302400cd06cff4c3
- https://github.com/strangerstudios/pmpro-gift-levels/commit/f322e79454e5426e07edeac57de0c586183d2cdc

**Analysis**
One of those commits is particularly interesting since it essentially undoes a commit that was previously added in v0.3, when the change log says that this issue was resolved for Stripe:
Original fixes:
- https://github.com/strangerstudios/pmpro-gift-levels/commit/22b2ddad33a0a54616f29882bbaa9447c438f7ce
- https://github.com/strangerstudios/pmpro-gift-levels/commit/edca62e337444087a5a394e72c8df25ac04e8e70

Commit that undoes those commits:
- https://github.com/strangerstudios/pmpro-gift-levels/commit/ac19ec8d7f2c1caa5545ce3d73f9807becc8d6b3

**Resolution**
I have confirmed that changing `add_action('pmpro_checkout_before_change_membership_level', 'pmprogl_pmpro_checkout_before_change_membership_level', 1);` to `add_action('pmpro_checkout_before_processing', 'pmprogl_pmpro_checkout_before_change_membership_level', 1);` resolves this issue for Stripe, though it would likely cause the PayPal issue again. More work will be needed to fix resolve this issue for both gateways at once, though I have put together a code recipe that will fix this behavior for Stripe in the meantime:
https://gist.github.com/dparker1005/1012fe4e6975d0a4220919ea66d5b848
