### ISSUE TITLE
Feature / Enhancement: Enable use of own codes

### ISSUE THREAD

**Issue by mircobabini** [strangerstudios/pmpro-gift-levels#33]
**Is your feature request related to a problem? Please describe.**
Yeah, should be possible to unhook the "using own code" check.

**Describe the solution you'd like**
I'd love to unhook that piece of logic, but it's into `pmprogl_pmpro_registration_checks` which does other checks.

**Describe alternatives you've considered**
There are two ways to move on:
1) Add a filter `if( apply_filters( 'pmprogl_avoid_use_own_gift_code', true ) ): `... (don't like it)
2) Instead of hooking everything into a single functions, split this into two functions.

https://github.com/strangerstudios/pmpro-gift-levels/blob/dev/pmpro-gift-levels.php#L308

to:

```
add_filter("pmpro_registration_checks", "pmprogl_pmpro_registration_check_own_code");
add_filter("pmpro_registration_checks", "pmprogl_pmpro_registration_check_require_gift_code");
```

I can send a pull request, just want to discuss the way you want it.

**Comment by dparker1005** [comment]
What is the use-case for wanting to allow users to use their own gift code? This seems fairly custom from what I can tell. There would need to be discussion about whether we want to encourage sites to do this.

One solution that would work now could be to unhook the current `pmprogl_pmpro_registration_checks()` function and then to hook a custom function in its place that only performs the "require gift code" check.

**Comment by mircobabini** [comment]
Sometimes customers goes for gifts instead of memberships, because their are just not reading what they are buying, even if written in capital letters.

In these cases, I provide them a custom link with ?allow-self-gift handled by some custom code which disables that logic.

This way we don't have to refund, which is complicated in Europe when alredy emitted invoices with unique numeration.

On high traffic websites, having this king of feature simplifies a lot the customer service work.

**Comment by dparker1005** [comment]
Instead of changing the `pmpro_registration_checks` logic, I think a quicker solution (that wouldn't require a code recipe on individual sites) would be for admins to:
1. Edit the user's gift code such that the code is not applicable to any levels
2. Give the user the membership level that the gift was originally for with an expiration date if necessary

I don't think it is necessary for the user to go through the checkout process again to get their membership, unless there are custom fields that need to be filled out or recurring payments that need to be set up. In this case, the admin can just create a regular discount code for the user to use that isn't a "gift code".

Does this sound like an ok workaround or do you still think that a solution in the code is necessary? My concern with the `?allow-self-gift` solution is that any user can use that URL param, not just the ones that you want to use it.

**Comment by mircobabini** [comment]
Late answer on this but want to provide my feedback.
1. Concerns about the workaround (query param): totally agree.
1. Proposed solutions: nice, but in my case it would take some extra steps (because I must also send a feedback about who used the code, and this is not possible if they don't actively consumes the code).

By the way, considering the [split registration checks into separate functions](https://github.com/strangerstudios/pmpro-gift-levels/pull/56), I can easily apply my "messy solution" which is cool, even if far from perfection.

It's interesting to focus on the consideration you've made:

> I don't think it is necessary for the user to go through the checkout process again to get their membership, unless there are custom fields that need to be filled out or recurring payments that need to be set up

Right. Since we know it's a gift, it would be great to show a veeeery simplified checkout process which shows:
- the gift code with some fancy design
- a "use now" button to consume it now

Since we know they are already logged in, if no additional fields are required... this is a custom implementation by the way.
