### ISSUE TITLE
Show warning if gift giver level has recurring payment or expiration date.

### ISSUE THREAD

**Issue by dparker1005** [strangerstudios/pmpro-gift-levels#38]
It usually does not make sense for a gift giver level to be recurring or expire as that membership level will not be linked with the membership level of the gift receiver. We should show a warning message if this is the case.

One exception to this rule is if you have a recurring membership level that happens to come with a trial for a friend. Not sure how popular of a use-case this would be.

**Comment by mircobabini** [comment]
> We should show a warning message if this is the case

You mean in the membership configuration page?

That use-case is probably rare and since membership configurations are very flexible, a warning is certainly needed. The fact is that the gift configuration still need to be done using code, instead of GUI. This way, it's possible that the warning is not seen by the administrator. Showing the warning out of the membership configuration page is invasive imo.

Then, this is what I think: 50% kudos to this one, which should be followed by some ideas to move the gift configuration logic into GUI, to be 100% effective and easy to understand.
