### ISSUE TITLE
Generate "Test" Discount Codes / Gift Codes

### ISSUE THREAD

**Issue by jeffdembinski** [strangerstudios/pmpro-gift-levels#4]
Is there a way to generate test discount codes to make sure my users REDEEMING the gift will not be prompted for a credit card number?

**Comment by andrewlimaza** [comment]
This issue is outdated, you may create a test user and purchase a level as a gift giver and then receive the gift code. You then can checkout as a new test user to see the redemption part of this.

This uses the default discount code functionality of PMPro and appends a G as a prefix to the discount code.
