### ISSUE TITLE
Gift Membership Warning shows for all levels

### ISSUE THREAD

**Issue by dparker1005** [strangerstudios/pmpro-gift-levels#59]
**Describe the bug**
The Gift Membership Warning should only show if the level being edited was set as a Gift Level, but it is currently showing for all levels with a recurring payment or expiration date.

**To Reproduce**
1. Edit a membership level with an expiration date or recurring payments, but that is not a gift level
2. See that the warning is shown

**Expected behavior**
The warning should not be shown in the above case.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only Paid Memberships Pro plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Memberlite](https://wordpress.org/themes/memberlite/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Please share non-sensitive information about your hosting environment such as WordPress version, PHP version, Paid Memberships Pro and any related plugins versions.
```
</details>

**Comment by dparker1005** [comment]
This line probably just needs to be updated to check that `$enabled` is true:
https://github.com/strangerstudios/pmpro-gift-levels/blob/d7ed00842e81c455781a2f6b8d7168f09b1bd167/includes/admin.php#L41

**Comment by michaelbeil** [comment]
Reported in ticket 411462 (**moderators only**).
>I have a warning on the “normal” product settings page. The warning is:
Gift Membership Warning: The settings of this level are not recommended. Remove the recurring subscription and membership expiration from this level. When it says “gift membership”, I suppose it’s related to the option to make it as a gift, isn’t it ? Because the option is not ticked on those “normal” products, I don’t understand why I have the warning. Can you explain what’s wrong ? I attach a screenshot of the settings of the “normal” product. On gift product settings, I have no warning.
